/** @type Promise<HTMLImageElement> */export const BackgroundYard = new Promise(r => {const x = new Image();x.onload = () => r(x);x.src = '/Images/BackgroundYard.jpg';});
/** @type Promise<HTMLImageElement> */export const GoalsIcon = new Promise(r => {const x = new Image();x.onload = () => r(x);x.src = '/Images/GoalsIcon.png';});
/** @type Promise<HTMLImageElement> */export const HawksbillTurtlesantahat = new Promise(r => {const x = new Image();x.onload = () => r(x);x.src = '/Images/HawksbillTurtle-santahat.png';});
/** @type Promise<HTMLImageElement> */export const HawksbillTurtletophat = new Promise(r => {const x = new Image();x.onload = () => r(x);x.src = '/Images/HawksbillTurtle-tophat.png';});
/** @type Promise<HTMLImageElement> */export const HawksbillTurtle = new Promise(r => {const x = new Image();x.onload = () => r(x);x.src = '/Images/HawksbillTurtle.png';});
/** @type Promise<HTMLImageElement> */export const MenuIcon = new Promise(r => {const x = new Image();x.onload = () => r(x);x.src = '/Images/MenuIcon.png';});
/** @type Promise<HTMLImageElement> */export const PetIcon = new Promise(r => {const x = new Image();x.onload = () => r(x);x.src = '/Images/PetIcon.png';});
/** @type Promise<HTMLImageElement> */export const ResourcesIcon = new Promise(r => {const x = new Image();x.onload = () => r(x);x.src = '/Images/ResourcesIcon.png';});
/** @type Promise<HTMLImageElement> */export const Saolasantahat = new Promise(r => {const x = new Image();x.onload = () => r(x);x.src = '/Images/Saola-santahat.png';});
/** @type Promise<HTMLImageElement> */export const Saolatophat = new Promise(r => {const x = new Image();x.onload = () => r(x);x.src = '/Images/Saola-tophat.png';});
/** @type Promise<HTMLImageElement> */export const Saola = new Promise(r => {const x = new Image();x.onload = () => r(x);x.src = '/Images/Saola.png';});
/** @type Promise<HTMLImageElement> */export const SettingsIcon = new Promise(r => {const x = new Image();x.onload = () => r(x);x.src = '/Images/SettingsIcon.png';});
/** @type Promise<HTMLImageElement> */export const ShopIcon = new Promise(r => {const x = new Image();x.onload = () => r(x);x.src = '/Images/ShopIcon.png';});
/** @type Promise<HTMLImageElement> */export const profile = new Promise(r => {const x = new Image();x.onload = () => r(x);x.src = '/Images/profile.png';});
export default {BackgroundYard,GoalsIcon,HawksbillTurtlesantahat,HawksbillTurtletophat,HawksbillTurtle,MenuIcon,PetIcon,ResourcesIcon,Saolasantahat,Saolatophat,Saola,SettingsIcon,ShopIcon,profile,};
